baseURL = "http://www.matheuscastiglioni.com.br/"
defaultContentLanguage = "pt-br"
disableKinds = ["taxonomyTerm"]
languageCode = "pt-br"
theme = "matheuscastiglioni"
title = "Matheus Castiglioni"

[params]
    author = "Matheus Castiglioni"
    authorWork = "Front-End Developer"
    photoPerfil = "https://res.cloudinary.com/mahenrique94/image/upload/v1549730047/matheus-castiglioni_ea9gn8.jpg"
