baseURL = "http://www.matheuscastiglioni.com.br/"
defaultContentLanguage = "pt-br"
disableKinds = ["taxonomyTerm"]
languageCode = "pt-br"
theme = "matheuscastiglioni"
title = "Matheus Castiglioni"

[params]
    author = "Matheus Castiglioni"
    authorWork = "Senior Software Engineer"
    photoPerfil = "https://res.cloudinary.com/mahenrique94/image/upload/v1648751979/Matheus_Avatar_YouTube_v1_2_akwzy1.jpg"
